Minor improvements
redphx/facebook-tweaker pull request #3
Opened 2017-03-13 15:13 UTC by J2TeaM

2017-03-18 11:43 UTC, redphx requested changes
@J2TeaM thanks for the PR. Can you update the code? Thanks.

2017-03-18 11:43 UTC, redphx commented on js/configs.js
> +              userConfigs: userConfigs
@J2TeaM please [keep all trailing commas](https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8)

2017-03-18 11:43 UTC, redphx commented on js/content-script.js
> +      fbConfigs: fbConfigs
@J2TeaM don't remove this too

2017-03-18 11:43 UTC, redphx commented on js/content-script.js
> +            if (ib !== null) kb = hb.stopTiming(ib);
@J2TeaM I want to keep all the code from line 21 to line 457 beacause they're from Fb's code.

2017-03-22 04:27 UTC, Daniel15 commented on js/content-script.js
> +            if (ib !== null) kb = hb.stopTiming(ib);
This change would make the code behave differently - `!= null` matches both `null` and `undefined`, whereas `!== null` only matches `null`.

2017-03-22 04:30 UTC, redphx commented on js/content-script.js
> +            if (ib !== null) kb = hb.stopTiming(ib);
@Daniel15 that's why I don't want to touch the original code

2017-03-22 13:38 UTC, J2TeaM commented
@redphx Updated!

2017-03-22 13:39 UTC, J2TeaM commented on js/configs.js
> +              userConfigs: userConfigs
@redphx thanks! I learned something new today 👍

2017-03-30 02:45 UTC, redphx commented
@J2TeaM thanks!

2017-03-30 02:45 UTC, merged